name: astro_mc_dart
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  complex: ^0.7.2
  csv: ^5.0.1

dev_dependencies:
  lints: ^1.0.0
